# Tipos de almacenamiento de datos en Python

- Listas--> []
- tuplas --> ()
- diccionarios --> {clave : valor}
- conjuntos (set) --> {,}
- dataframe --> tabla
- matrices --> [[],[]]

Formatos:
- entero --> int
- decimales --> float
- objetos --> obj
- cadena de texto --> str
- boleanos --> True/ False

## Listas

In [1]:
lista = [1, 5, 6, 8, None, 6, None]

lista

[1, 5, 6, 8, None, 6, None]

In [2]:
lista[0], lista[1], lista[2]

(1, 5, 6)

In [3]:
lista[-1], lista[-2]

(None, 6)

In [4]:
lista[-3] = 3
lista

[1, 5, 6, 8, 3, 6, None]

In [5]:
lista.append(10)
lista

[1, 5, 6, 8, 3, 6, None, 10]

## Tuplas

In [6]:
valor = (1, 5, 10, 60,)
valor

(1, 5, 10, 60)

In [7]:
type(valor)

tuple

In [8]:
valor[1]

5

In [9]:
valor[1] = 10

TypeError: 'tuple' object does not support item assignment

In [10]:
valor.append(10)

AttributeError: 'tuple' object has no attribute 'append'

In [11]:
valor2 = (5)
type(valor2)

int

In [12]:
valor2 = (5, )
type(valor2)

tuple

In [13]:
valor_final = valor + valor2
valor_final

(1, 5, 10, 60, 5)

## Matriz

In [14]:
import numpy as np

matriz = np.array([1, 2, 50, 60])
matriz

array([ 1,  2, 50, 60])

In [15]:
matriz[2]

np.int64(50)

In [16]:
matriz = np.append(matriz, 20)
matriz

array([ 1,  2, 50, 60, 20])

In [17]:
matriz[2] = 100
matriz

array([  1,   2, 100,  60,  20])

In [18]:
matriz = np.array([[1, 2], [3, 4]])
matriz

array([[1, 2],
       [3, 4]])

In [19]:
matriz[0][1]

np.int64(2)

## Diccionarios

In [20]:
# diccionario: clave-valor
# {'clave': 'valor'}
# {'clave1': 'valor1', 'clave2': 'valor2'}

diccionario = {'1': 25, '2': 30}
diccionario

{'1': 25, '2': 30}

In [21]:
diccionario['2']

30

In [22]:
diccionario['3'] = 400
diccionario

{'1': 25, '2': 30, '3': 400}

In [23]:
diccionario['1'] = 500
diccionario

{'1': 500, '2': 30, '3': 400}

In [24]:
diccionario2 = dict(Estudiantes=lista)
diccionario2

{'Estudiantes': [1, 5, 6, 8, 3, 6, None, 10]}

## Dataframes

In [25]:
import pandas as pd

data = {'Nombre': lista}
df = pd.DataFrame(data)
df

Nombre
0     1.0
1     5.0
2     6.0
3     8.0
4     3.0
5     6.0
6     NaN
7    10.0

## Formatos

In [26]:
# enteros:

x = 10
print(type(x),':', x)

<class 'int'> : 10


In [27]:
# float siempre se escribe con punto (.)
# sino sería una tupla:

y = 1,2
print(type(y))

y = 1.2
print(type(y), ':', y)

# abreviamos mediante el .X, significa un cero delante:
y = .5
print(y)

<class 'tuple'>
<class 'float'> : 1.2
0.5


In [28]:
# string

texto = 'Hola Mundo'
print(texto)
texto = "Hola Mundo"
print(texto)

# Alternar comillas dobles con simples o viceversa:
texto = "Hola 'Mundo'"
print(texto)

# Se una el simbolo de escape para usar comillas simples fuera y dentro:
texto = 'Hola \'Mundo\''
print(texto)

# concatenacion:
texto = "Hola" + " " + "Mundo"
print(texto)

# Extraer los caracteres:
texto[2]

Hola Mundo
Hola Mundo
Hola 'Mundo'
Hola 'Mundo'
Hola Mundo


'l'

In [29]:
x = 'abcd'
x = '-'.join(x)
x

'a-b-c-d'

In [30]:
# Boleanos

x = True
print(type(x), ':', x)
y = False
print(type(y), ':', y)

<class 'bool'> : True
<class 'bool'> : False


## Gestión de archivos usando el método Open

In [31]:
file = open('contact.csv', 'r', encoding='utf-8')
file.read()
file.close()

FileNotFoundError: [Errno 2] No such file or directory: 'contact.csv'

'r' --> solo lectura, error

'w' --> lees y sobreescribes, si no existe lo genera

'a' --> lees y apendizas, si no existe lo genera

In [32]:
import json

electron = 1.602176620898E10
elect = json.dumps(electron)
print(type(elect))

<class 'str'>


In [33]:
import json

comics = '"The Meaning of Life" by Monty Python\'s Flying Circus'
print(type(json.dumps(comics)))

<class 'str'>


In [34]:
import json

my_list = [1, 2.34, True, "False", None, ['a', 0]]
print(json.dumps(my_list))
print(type(json.dumps(my_list)))

[1, 2.34, true, "False", null, ["a", 0]]
<class 'str'>


In [35]:
import json

jstr = '16021766189.98'
electron = json.loads(jstr)
print(type(electron))
print(electron)

<class 'float'>
16021766189.98


In [36]:
import json

jstr = '"\\"The Meaning of Life\\" by Monty Python\'s Flying Circus"'
comics = json.loads(jstr)
print(type(comics))
print(comics)

<class 'str'>
"The Meaning of Life" by Monty Python's Flying Circus


In [37]:
import json

json_str = '{"me":"Python","pi":3.141592653589, "data":[1,2,4,8],"friend":"JSON","set": null}'
my_dict = json.loads(json_str)
print(type(my_dict))
print(my_dict['set'])

<class 'dict'>
None


## Atributos de print:

In [38]:
texto1 = 'Hola'
texto2 = 'Mundo'

print(texto1, texto2, end='*')
print('\n')
print(texto1, texto2, sep='*')

Hola Mundo*

Hola*Mundo


## Método range: generar valores

In [39]:
# range(inicio, stop, step)
# range(0, 9 + 1, 1):

list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [40]:
# range(inicio, stop, step)
# range(0, 9 + 1, 1):

list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [41]:
for valor in range(10):
    print(valor)

0
1
2
3
4
5
6
7
8
9
